#!/usr/bin/env node

/**
 * Development Setup Script
 * Helps configure the development environment for testing payments
 */

const fs = require('fs');
const path = require('path');

console.log('🛠️  Superfocus Development Setup\n');

// Check if .env.local already exists
const envPath = path.join(__dirname, '..', '.env.local');
if (fs.existsSync(envPath)) {
    console.log('⚠️  .env.local already exists. Backing up to .env.local.backup');
    fs.copyFileSync(envPath, envPath + '.backup');
}

// Create .env.local template
const envTemplate = `# Development Environment Variables
# Generated by setup-dev.js

# Stripe Test Mode Keys (get these from https://dashboard.stripe.com/test/apikeys)
STRIPE_SECRET_KEY=sk_test_your_test_secret_key_here
STRIPE_PRICE_ID=price_your_test_price_id_here
STRIPE_WEBHOOK_SECRET=whsec_your_test_webhook_secret_here

# Clerk Development Keys (get these from https://dashboard.clerk.com/)
CLERK_PUBLISHABLE_KEY=pk_test_your_clerk_publishable_key_here
CLERK_SECRET_KEY=sk_test_your_clerk_secret_key_here

# Development URLs
STRIPE_SUCCESS_URL=http://localhost:3000?premium=1&payment=success
STRIPE_CANCEL_URL=http://localhost:3000
STRIPE_RETURN_URL=http://localhost:3000
STRIPE_PORTAL_CONFIGURATION_ID=pmc_your_test_portal_config_id_here

# Todoist (optional for development)
TODOIST_CLIENT_ID=your_todoist_client_id_here
TODOIST_CLIENT_SECRET=your_todoist_client_secret_here
`;

fs.writeFileSync(envPath, envTemplate);

console.log('✅ Created .env.local template');
console.log('\n📋 Next steps:');
console.log('1. Get your Stripe test keys from: https://dashboard.stripe.com/test/apikeys');
console.log('2. Get your Clerk dev keys from: https://dashboard.clerk.com/');
console.log('3. Update the values in .env.local');
console.log('4. Run: npm run dev');
console.log('\n💳 Test cards:');
console.log('• 4242 4242 4242 4242 (Visa - Success)');
console.log('• 4000 0000 0000 0002 (Visa - Declined)');
console.log('• 5555 5555 5555 4444 (Mastercard - Success)');
console.log('\n🚀 Happy testing!');
